export const GET_CABANA = 'GET_CABANA';
export const GET_CABANA_EXITO = 'GET_CABANA_EXITO';
export const GET_CABANA_FALLO = 'GET_CABANA_FALLO';

export const ADD_CABANA = 'ADD_CABANA';
export const ADD_CABANA_EXITO = 'ADD_CABANA_EXITO';
export const ADD_CABANA_FALLO = 'ADD_CABANA_FALLO';

export const EDIT_CABANA = 'EDIT_CABANA';
export const EDIT_CABANA_EXITO = 'EDIT_CABANA_EXITO';
export const EDIT_CABANA_FALLO = 'EDIT_CABANA_FALLO';

export const DELETE_CABANA = 'DELETE_CABANA';
export const DELETE_CABANA_EXITO = 'DELETE_CABANA_EXITO';
export const DELETE_CABANA_FALLO = 'DELETE_CABANA_FALLO';


 